# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [96]:
# Exercise 1
import numpy as np

Values_arr1 = np.arange(1, 11)
print(Values_arr1)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [97]:
# Exercise 2
Values_arr2 = np.zeros((3, 3))
print(Values_arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [98]:
# Exercise 3
Values_arr3 = np.linspace(0, 5, 10)
print(Values_arr3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [99]:
# Exercise 4
Values_arr4 = np.eye(5)
print(Values_arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [106]:
# Exercise 5
Values_arr5 = np.random.rand(4, 4)
print(Values_arr5)

[[0.79203504 0.98374485 0.29083307 0.92071282]
 [0.30292658 0.54557849 0.15563386 0.78090437]
 [0.78003751 0.80396343 0.4736155  0.80392093]
 [0.09608968 0.58463076 0.78548879 0.1718931 ]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [107]:
# Exercise 6
Values_arr6 = np.array([[1, 2, 3], [4, 5, 6]])
print(Values_arr6.shape)

(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [105]:
# Exercise 7
Values_arr7 = np.arange(16).reshape(4, 4)
print(Values_arr7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [103]:
# Exercise 8
Values_arr8 = np.array([1.5, 2.3, 3.9])
print(Values_arr8.dtype)

float64



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [104]:
# Exercise 9
Values_arr9 = np.arange(1, 101)
even_numbers = Values_arr9[Values_arr9 % 2 == 0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [108]:
# Exercise 10
Values_arr10 = np.random.randint(10, 51, size=(6, 6))
print(Values_arr10)

[[14 41 14 21 10 45]
 [49 23 29 28 50 36]
 [41 40 12 10 11 47]
 [27 30 31 22 40 11]
 [17 26 32 26 15 35]
 [29 12 39 13 15 50]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [111]:
# Exercise 11
Values_arr11 = np.arange(1, 17).reshape(4, 4)
submatrix = Values_arr11[1:3, 1:3]  
print("Original:\n", Values_arr11)
print("Submatrix:\n", submatrix)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Submatrix:
 [[ 6  7]
 [10 11]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [112]:
# Exercise 12
Values_arr12 = np.array([[1, 2], [3, 4]])
total_sum = Values_arr12.sum()
print(total_sum)

10



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [113]:
# Exercise 13
Valuses_arr13 = np.array([10, 20, 30, 40, 50])

mean = np.mean(Valuses_arr13)
median = np.median(Valuses_arr13)
std_dev = np.std(Valuses_arr13)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [114]:
# Exercise 14
Values_arr14 = np.array([5, 3, 8, 1, 9])
max_val = np.max(Values_arr14)
min_val = np.min(Values_arr14)

print("Max:", max_val)
print("Min:", min_val)

Max: 9
Min: 1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [115]:
# Exercise 15
Values_arr15 = np.random.randint(1, 100, size=20)
index_of_max = np.argmax(arr15)

print("Array:", Values_arr15)
print("Index of max value:", index_of_max)

Array: [12 74 47 60 39  5 95 84 86 81 47 76 35 77 52 35 18 50  6 87]
Index of max value: 0



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [116]:
# Exercise 16
Values_arr16 = np.array([1, 2, 3, 4, 5])
reversed_arr = Values_arr16[::-1]

print("Reversed array:", reversed_arr)

Reversed array: [5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [22]:
# Exercise 17
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

elementwise_product = matrix1 * matrix2
print("Element-wise multiplication:\n", elementwise_product)

Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [117]:
# Exercise 18
Values_arr18 = np.array([10, 20, 30, 40])
diag_matrix = np.diag(Values_arr18)

print("Diagonal matrix:\n", diag_matrix)

Diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [25]:
# Exercise 19
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(A, B)  # or A @ B
print("Matrix multiplication:\n", matrix_product)

Matrix multiplication:
 [[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [118]:
# Exercise 20
Values_arr20 = np.array([[1, 2], [3, 4], [5, 6]])
flattened = Values_arr20.flatten()

print("Flattened array:", flattened)

Flattened array: [1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [27]:
# Exercise 21
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical_stack = np.vstack((a, b))
print("Vertically stacked:\n", vertical_stack)

Vertically stacked:
 [[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [28]:
# Exercise 22
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

horizontal_stack = np.hstack((a, b))
print("Horizontally stacked:\n", horizontal_stack)

Horizontally stacked:
 [[1 4]
 [2 5]
 [3 6]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [119]:
# Exercise 23
Values_arr23 = np.arange(10)
split_arr = np.array_split(Values_arr23, 3)  # Splits into 3 parts

for i, part in enumerate(split_arr, 1):
    print("Sub-array {i}:", part)

Sub-array {i}: [0 1 2 3]
Sub-array {i}: [4 5 6]
Sub-array {i}: [7 8 9]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [120]:
# Exercise 24
Values_arr24 = np.random.rand(4, 4)
rounded_arr = np.round(Values_arr24, 2)

print("Rounded array:\n", rounded_arr)

Rounded array:
 [[0.18 0.06 0.18 0.44]
 [0.26 0.25 0.6  0.03]
 [0.68 0.43 0.21 0.42]
 [0.55 0.27 0.54 0.03]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [121]:
# Exercise 25
Values_arr25 = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_elements = np.unique(Values_arr25)

print("Unique elements:", unique_elements)

Unique elements: [1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [122]:
# Exercise 26
Values_arr26 = np.array([3, 7, 1, 9, 2, 5])
arr26[Values_arr26 < 4] = 4 

print("Modified array:", Values_arr26)

Modified array: [3 7 1 9 2 5]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [123]:
# Exercise 27
Values_arr27 = np.array([1, 2, 3, 4])
cumsum = np.cumsum(Values_arr27)

print("Cumulative sum:", cumsum)

Cumulative sum: [ 1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [124]:
# Exercise 28
Values_arr28 = np.array([0, 3, 0, 7, 1, 0, 9])
nonzero_count = np.count_nonzero(Values_arr28)

print("Number of non-zero elements:", nonzero_count)

Number of non-zero elements: 4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [125]:
# Exercise 29
Values_arr29 = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(Values_arr29)

print("Original array:", Values_arr29)
print("Sorted array:", sorted_arr)

Original array: [46 22 68 48 95 14 63 15 55 87]
Sorted array: [14 15 22 46 48 55 63 68 87 95]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [126]:
# Exercise 30
Values_arr30 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
row_sum = np.sum(Values_arr30, axis=1)
col_sum = np.sum(Values_arr30, axis=0)

print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [127]:
# Exercise 31
Values_arr31 = np.random.rand(3, 3) * 100  # Random values from 0 to 100
normalized = (arr31 - np.min(Values_arr31)) / (np.max(Values_arr31) - np.min(Values_arr31))

print("Original:\n", Values_arr31)
print("Normalized:\n", np.round(normalized, 2))

Original:
 [[81.43687337 47.9249904  34.33281246]
 [60.5995435  88.68855228 29.02925419]
 [72.65089555 86.47694645  3.80700929]]
Normalized:
 [[ 0.98  0.28  0.31]
 [ 0.24  0.89  0.65]
 [ 0.88  0.45 -0.  ]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [41]:
# Exercise 32
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b) 
print("Dot product:", dot_product)

Dot product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [42]:
# Exercise 33
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace = np.trace(matrix)
print("Trace of the matrix:", trace)

Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [128]:
# Exercise 34
Value_sarr34 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap row 0 and row 2
Value_sarr34[[0, 2]] = Value_sarr34[[2, 0]]
print("After swapping rows:\n", Value_sarr34)

After swapping rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [46]:
Column_convert = np.array([10, 20, 30, 40])
Column_Vector = Column_convert.reshape(-1, 1)
print ("Column_Vector:\n", Column_Vector)

Column_Vector:
 [[10]
 [20]
 [30]
 [40]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [129]:
# Exercise 36
Matrix_determinant = np.array([[2, 3, 1],
                               [4, 1, 5],
                               [7, 2, 6]])
determinant = np.linalg.det(Matrix_determinant)
print("determinant:", round(determinant, 2))

determinant: 26.0



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [61]:
# Exercise 37:
import numpy as np

matrix37 = np.array([[4, 2],
                     [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix37)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [4.56155281 0.43844719]
Eigenvectors:
 [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [62]:
# Exercise 38
A = np.array([[2,3],
             [3, 4]])

b = np.array([8, 11])

solution = np.linalg.solve(A, b)
print("Solution [x, y]:", solution)

Solution [x, y]: [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [66]:
# Exercise 39
Gaussian_array = np.array([10, 20, 30, 40, 50], dtype=float)
noise = np.random.normal(loc=0, scale=5, size=Gaussian_array.shape) 

noisy_arr = Gaussian_array + noise
print("Original array:", Gaussian_array)
print("With Gaussian noise:", np.round(noisy_arr, 2))

Original array: [10. 20. 30. 40. 50.]
With Gaussian noise: [ 7.57 18.2  27.51 37.46 49.37]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [67]:
# Exercise 40
Elements = np.array([[5, 1, 2, 3],
                     [4, 6, 7, 8],
                     [9, 0, 3, 2],
                     [1, 4, 6, 7]])

diagonal = np.diag(Elements)
print("Diagonal elements:", diagonal)

Diagonal elements: [5 6 3 7]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [68]:
# Exercise 41
Random_array = np.random.randint(0, 100, size=100)
clipped_arr = np.clip(Random_array, 10, 50)

print("Original values (first 10):", Random_array[:10])
print("Clipped values (first 10):", clipped_arr[:10])

Original values (first 10): [ 0 80 48 78 62 21 42 64 26 86]
Clipped values (first 10): [10 50 48 50 50 21 42 50 26 50]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [69]:
# Exercise 42
Replace_array = np.array([[5, -9, -1],
                         [10, -11, 3]])
Replace_array[Replace_array < 0] = 0
print("Replaced negative with zero:\n", Replace_array)

Replaced negative with zero:
 [[ 5  0  0]
 [10  0  3]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [70]:
# Exercise 43
a = np.array([1, 2])
b = np.array([3, 4])

inner_product = np.inner(a, b)
outer_product = np.outer(a, b)

print("Inner product:", inner_product)
print("Outer product:\n", outer_product)

Inner product: 11
Outer product:
 [[3 4]
 [6 8]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [71]:
# Exercise 44
from scipy.spatial.distance import pdist, squareform

points = np.array([[1, 2],
                   [4, 6],
                   [7, 8]])

pairwise_distances = squareform(pdist(points, metric='euclidean'))

print("Pairwise distances:\n", np.round(pairwise_distances, 2))

Pairwise distances:
 [[0.   5.   8.49]
 [5.   0.   3.61]
 [8.49 3.61 0.  ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [72]:
# Exercise 45
data = np.array([("Alice", 25, 165.5),
                 ("Bob", 30, 175.0),
                 ("Charlie", 22, 180.2)],
                dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

print("Structured array:\n", data)
print("Names:", data['name'])
print("Ages:", data['age'])
print("Heights:", data['height'])


Structured array:
 [('Alice', 25, 165.5) ('Bob', 30, 175. ) ('Charlie', 22, 180.2)]
Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Heights: [165.5 175.  180.2]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [73]:
# Exercise 46
Values = np.random.randint(0, 10, (5, 5))
unique, counts = np.unique(Values, return_counts=True)

print("Matrix:\n", Values)
print("Value counts:")
for val, count in zip(unique, counts):
    print(f"{val}: {count}")

Matrix:
 [[0 1 2 1 7]
 [9 6 1 6 0]
 [0 7 6 7 8]
 [7 3 5 2 6]
 [2 4 0 5 5]]
Value counts:
0: 4
1: 3
2: 3
3: 1
4: 1
5: 3
6: 4
7: 4
8: 1
9: 1



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [130]:
# Exercise 47
Values_arr47 = np.random.rand(3, 3)
row_means = Values_arr47.mean(axis=1, keepdims=True)
centered = Values_arr47 - row_means

print("Original value:\n", np.round(Values_arr47, 2))
print("Row-centered value:\n", np.round(centered, 2))

Original value:
 [[0.04 1.   0.26]
 [0.4  0.17 0.68]
 [0.09 0.04 0.89]]
Row-centered value:
 [[-0.39  0.57 -0.17]
 [-0.02 -0.25  0.27]
 [-0.25 -0.3   0.55]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [131]:
# Exercise 48
Values_arr48 = np.random.randint(0, 100, size=10)
Check_values_greater_than50 = np.any(Values_arr48 > 50)

print("Array:", Values_arr48)
print("Any value that is greater than 50?:", Check_values_greater_than50)

Array: [ 0 30  0 40 63 10 13 41  0 80]
Any value that is greater than 50?: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [132]:
# Exercise 49
import numpy as np

values_arr49 = np.array([10, 20, 30, 40, 50]) 
window_size = 3

moving_avg = np.convolve(values_arr49, np.ones(window_size) / window_size, mode='valid')
print("Moving average:", moving_avg)

Moving average: [20. 30. 40.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [80]:
# Exercise 50:
x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

correlation_matrix = np.corrcoef(x, y)
pearson_corr = correlation_matrix[0, 1]

print("Pearson correlation coefficient:", pearson_corr)

Pearson correlation coefficient: 1.0



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [81]:
# Exercise 51
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)

print("Radians:", radians)
print("Degrees:", degrees)

Radians: [0.         0.52359878 0.78539816 1.57079633 3.14159265]
Degrees: [  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [82]:
# Exercise 52
Values_arr52 = np.random.randint(0, 100, size=10)
variance = np.var(Values_arr52)
std_dev = np.std(Values_arr52)

print("Array:", Values_arr52)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Array: [24 54 81 11 99 35 52 39 44 36]
Variance: 609.45
Standard Deviation: 24.68704113497606



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [83]:
# Exercise 53
Value_arr53 = np.array([[10, 25, 3],
                  [4, 15, 6],
                  [9, 18, 30]])

max_indices_rows = np.argmax(Value_arr53, axis=1)  
max_indices_cols = np.argmax(Value_arr53, axis=0)  

print("Array:\n", Value_arr53)
print("Indices of max values along rows:", max_indices_rows)
print("Indices of max values along columns:", max_indices_cols)

Array:
 [[10 25  3]
 [ 4 15  6]
 [ 9 18 30]]
Indices of max values along rows: [1 1 2]
Indices of max values along columns: [0 0 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [84]:
# Exercise 54
Value_arr54 = np.array([[4, 7],
                     [2, 6]])

inverse_matrix = np.linalg.inv(Value_arr54)

print("Original matrix:\n", Value_arr54)
print("Inverse matrix:\n", np.round(inverse_matrix, 2))

Original matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [86]:
# Exercise 55
Value_arr55 = np.random.rand(10)
standardized = (Value_arr55 - np.mean(Value_arr55)) / np.std(Value_arr55)

print("Original array:", np.round(Value_arr55, 2))
print("Standardized array:", np.round(standardized, 2))

Original array: [0.59 0.14 0.87 0.91 0.94 0.45 0.28 0.08 0.4  0.46]
Standardized array: [ 0.25 -1.25  1.21  1.35  1.45 -0.22 -0.79 -1.46 -0.37 -0.18]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [88]:
# Exercise 56
A56 = np.array([5, 10, 15])
B56 = np.array([2, 4, 6])

sum_result = A56 + B56
diff_result = A56 - B56

print("Element-wise addition:", sum_result)
print("Element-wise subtraction:", diff_result)

Element-wise addition: [ 7 14 21]
Element-wise subtraction: [3 6 9]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [90]:
# Exercise 57
Value_arr57 = np.random.rand(10)
max_index = np.argmax(Value_arr57)

print("Array:", np.round(Value_arr57, 2))
print("Index of maximum element:", max_index)
print("Maximum value:", Value_arr57[max_index])

Array: [0.43 0.27 0.15 0.25 0.29 0.76 0.83 0.84 0.56 0.14]
Index of maximum element: 7
Maximum value: 0.8449117874217255



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [92]:
# Exercise 58
Value_arr58 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

rotated = np.rot90(Value_arr58)

print("Original array:\n", Value_arr58)
print("Rotated 90° counterclockwise:\n", rotated)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated 90° counterclockwise:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [93]:
# Exercise 59
Value_arr59 = np.array([[1, 2],
                     [3, 4]])

fro_norm = np.linalg.norm(Value_arr59)

print("Matrix:\n", Value_arr59)
print("Frobenius norm:", round(fro_norm, 2))

Matrix:
 [[1 2]
 [3 4]]
Frobenius norm: 5.48



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [95]:
# Exercise 60
Value_arr60 = np.random.randint(0, 10, (3, 4, 5))

subarray = Value_arr60[:2, :2, :3]

print("Original 3D array shape:", Value_arr60.shape)
print("Sliced subarray shape:", subarray.shape)
print("Subarray:\n", subarray)

Original 3D array shape: (3, 4, 5)
Sliced subarray shape: (2, 2, 3)
Subarray:
 [[[6 8 2]
  [6 2 2]]

 [[9 7 1]
  [2 7 9]]]



---